name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cmake -S . -B .\bin\Release
        cd .\bin\Release
        make --config Release
    - name: run
      run: .\bin\Release\dmf2mod.exe
  
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cmake -S . -B ./bin/Release
        cd ./bin/Release
        make
    - name: run
      run: ./bin/Release/dmf2mod
      
  build-macOS:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cmake -S . -B ./bin/Release
        cd ./bin/Release
        make
    - name: run
      run: ./bin/Release/dmf2mod
