name: build
on: [push, pull_request]
jobs:
  build-windows:
    name: windows-x86_64
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake --preset console
    - name: Build
      run: cmake --build --preset console
    - name: Run
      run: .\build\console\Release\dmf2mod.exe
  build-linux:
    name: linux-x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake --preset console
    - name: Build
      run: cmake --build --preset console
    - name: Run
      run: ./build/console/dmf2mod
  build-macos:
    name: macos-arm64
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake --preset console
    - name: Build
      run: cmake --build --preset console
    - name: Run
      run: ./build/console/dmf2mod
