name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make
    - name: run
      run: .\dmf2mod.exe
  
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make
    - name: run
      run: ./dmf2mod
      
  build-macOS:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make
    - name: run
      run: ./dmf2mod
