name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v9

      - name: Verify Emscripten
        run: emcc -v

      - name: Build web app
        run: |
          emcmake cmake -DCMAKE_BUILD_TYPE=Release -S . -B ./bin/webapp
          emcmake cmake --build .

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bin/webapp
