name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 'latest'
          actions-cache-folder: 'emsdk-cache'

      - name: Verify Emscripten
        run: emcc -v

      - name: Build web app
        run: |
          emcmake cmake -S. -Bbin/webapp
          emmake make --dir=bin/webapp

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bin/webapp/html
          exclude_assets: '*.txt,CMakeFiles,*.cmake,Makefile'
