name: GitHub Pages
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 'latest'
          actions-cache-folder: 'emsdk-cache'
      - name: Verify Emscripten
        run: emcc -v
      - name: Configure
        run: cmake --preset web-app
      - name: Build
        run: cmake --build --preset web-app
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web-app/html
          exclude_assets: '*.txt,CMakeFiles,*.cmake,Makefile'
